export interface ScoringFlujoCajaLibre {

  codScoringFlujoCaja: number,
  codAnalisis: number,
  codActividadEconomica?: number,
  codPersona: number,
  fechaCreacion: Date,
  fechaModificacion?: Date,
  scofclEstado?: boolean,
  flujoEfectivoInicial: number,
  ingresosMensualesActividad: number,
  gastosNegocio: number,
  gastosPersonalesFamiliares: number,
  cuotasPrestamosSistema: number,
  nuevaObligacion: number,
  cuotaMonedaExtraAno1: number,
  cuotaMonedaExtraAno2: number,
  mesesProyectarObligaciones: number,
  ajusteSalario: number,
  saldoTotalDeudaAnoBase: number,
  saldoTotalDeudaAno2: number,
  valorPatrimonioActual: number,
  valorPatrimonioFuturoEstimado: number,
  ahorroNuevaObligacion: number,
  requerimietoCapitalTrabajo: number,
  otrosIngresosIndirectos: number,
  mejoradorCrediticio: number,
  aporteEfectivo: number,
  otrosGastosIndirectos: number,
  scodfclCodDescripcionReporte: number,
  scofclDescripcion: string,
  usuarioCreacion: string,
  usuarioModificacion?: string,
  observacionValorPatrimonio: string,

}
